services:
  paddle-ocr-api:
    image: ${PADDLE_OCR_IMAGE:-paddle-ocr-api-gpu:latest}
    pull_policy: never
    environment:
      PADDLE_OCR_DEVICE: gpu:0
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    gpus: all
