"""create p1 master data tables

Revision ID: 99964e1c3f42
Revises:
Create Date: 2026-04-30 17:14:48.523119

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99964e1c3f42"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dictionaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dict_type", sa.String(length=80), nullable=False),
        sa.Column("value", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dict_type", "value", name="uq_dictionaries_type_value"),
    )
    op.create_index(op.f("ix_dictionaries_dict_type"), "dictionaries", ["dict_type"], unique=False)
    op.create_index(op.f("ix_dictionaries_id"), "dictionaries", ["id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_code"), "projects", ["code"], unique=True)
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_table(
        "centers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("contact_person", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "code", name="uq_centers_project_code"),
    )
    op.create_index(op.f("ix_centers_id"), "centers", ["id"], unique=False)
    op.create_index(op.f("ix_centers_project_id"), "centers", ["project_id"], unique=False)
    op.create_table(
        "stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "code", name="uq_stages_project_code"),
    )
    op.create_index(op.f("ix_stages_id"), "stages", ["id"], unique=False)
    op.create_index(op.f("ix_stages_project_id"), "stages", ["project_id"], unique=False)
    op.create_table(
        "stage_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=150), nullable=False),
        sa.Column("item_code", sa.String(length=80), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stage_id"], ["stages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "stage_id", "item_code", name="uq_stage_templates_item"),
    )
    op.create_index(op.f("ix_stage_templates_id"), "stage_templates", ["id"], unique=False)
    op.create_index(
        op.f("ix_stage_templates_project_id"), "stage_templates", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_stage_templates_stage_id"), "stage_templates", ["stage_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stage_templates_stage_id"), table_name="stage_templates")
    op.drop_index(op.f("ix_stage_templates_project_id"), table_name="stage_templates")
    op.drop_index(op.f("ix_stage_templates_id"), table_name="stage_templates")
    op.drop_table("stage_templates")
    op.drop_index(op.f("ix_stages_project_id"), table_name="stages")
    op.drop_index(op.f("ix_stages_id"), table_name="stages")
    op.drop_table("stages")
    op.drop_index(op.f("ix_centers_project_id"), table_name="centers")
    op.drop_index(op.f("ix_centers_id"), table_name="centers")
    op.drop_table("centers")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_code"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_dictionaries_id"), table_name="dictionaries")
    op.drop_index(op.f("ix_dictionaries_dict_type"), table_name="dictionaries")
    op.drop_table("dictionaries")
    # ### end Alembic commands ###
