from dataclasses import dataclass


@dataclass(frozen=True)
class PermissionSpec:
    code: str
    label: str
    module: str
    description: str = ""


PERMISSIONS = [
    PermissionSpec("master_data:read", "查看主数据", "master_data"),
    PermissionSpec("master_data:write", "维护主数据", "master_data"),
    PermissionSpec("dictionaries:read", "查看状态字典", "dictionaries"),
    PermissionSpec("dictionaries:write", "维护状态字典", "dictionaries"),
    PermissionSpec("users:read", "查看用户", "identity"),
    PermissionSpec("users:write", "维护用户", "identity"),
    PermissionSpec("roles:read", "查看角色", "identity"),
    PermissionSpec("roles:write", "维护角色", "identity"),
    PermissionSpec("permissions:read", "查看权限", "identity"),
    PermissionSpec("clinical_data:read", "查看临床数据集", "clinical_data"),
    PermissionSpec("clinical_data:write", "维护临床数据集", "clinical_data"),
    PermissionSpec("clinical_data:delete", "删除受试者", "clinical_data"),
    PermissionSpec("pdf_packets:read", "查看PDF资料包", "pdf_packets"),
    PermissionSpec("pdf_packets:write", "处理PDF资料包", "pdf_packets"),
    PermissionSpec("pdf_packets:delete", "删除PDF资料包", "pdf_packets"),
    PermissionSpec("pdf_review:read", "查看PDF在线审阅", "pdf_review"),
    PermissionSpec("pdf_review:annotate", "维护PDF批注", "pdf_review"),
    PermissionSpec("pdf_review:manage", "管理PDF审阅", "pdf_review"),
    PermissionSpec("correction_tasks:read", "查看整改任务", "correction_tasks"),
    PermissionSpec("correction_tasks:create", "创建整改任务", "correction_tasks"),
    PermissionSpec("correction_tasks:submit", "提交整改资料", "correction_tasks"),
    PermissionSpec("correction_tasks:review", "复审整改任务", "correction_tasks"),
    PermissionSpec("files:read", "查看和下载文件", "files"),
    PermissionSpec("files:write", "上传和替换文件", "files"),
    PermissionSpec("files:delete", "删除文件", "files"),
    PermissionSpec("image_data:read", "查看图像数据", "image_data"),
    PermissionSpec("image_data:upload_raw", "上传原始图像", "image_data"),
    PermissionSpec("image_data:copy_raw", "下载原始图像副本", "image_data"),
    PermissionSpec("image_data:upload_enhanced", "上传增强图像", "image_data"),
    PermissionSpec("image_data:upload_report", "上传电子报告", "image_data"),
    PermissionSpec("image_data:delete", "删除图像数据", "image_data"),
    PermissionSpec("reviews:read", "查看审核记录", "reviews"),
    PermissionSpec("reviews:submit", "提交资料审核", "reviews"),
    PermissionSpec("reviews:review", "审核资料", "reviews"),
    PermissionSpec("completeness:read", "查看完整性", "completeness"),
    PermissionSpec("completeness:recalculate", "重算完整性", "completeness"),
    PermissionSpec("dashboard:read", "查看数据看板", "dashboard"),
    PermissionSpec("dashboard:write", "维护数据看板", "dashboard"),
    PermissionSpec("imports:read", "下载导入模板", "excel"),
    PermissionSpec("imports:write", "批量导入数据", "excel"),
    PermissionSpec("exports:read", "导出数据报表", "excel"),
    PermissionSpec("operation_logs:read", "查看操作日志", "audit"),
]

ROLE_SPECS = {
    "admin": {
        "label": "管理员",
        "description": "系统全局管理",
        "permissions": [permission.code for permission in PERMISSIONS],
    },
    "project_manager": {
        "label": "项目负责人",
        "description": "管理指定项目",
        "permissions": [
            "master_data:read",
            "dictionaries:read",
            "clinical_data:read",
            "clinical_data:write",
            "pdf_packets:read",
            "pdf_packets:write",
            "pdf_review:read",
            "pdf_review:annotate",
            "pdf_review:manage",
            "correction_tasks:read",
            "correction_tasks:create",
            "correction_tasks:submit",
            "correction_tasks:review",
            "files:read",
            "files:write",
            "files:delete",
            "image_data:read",
            "image_data:upload_raw",
            "image_data:copy_raw",
            "image_data:upload_enhanced",
            "image_data:upload_report",
            "image_data:delete",
            "reviews:read",
            "reviews:submit",
            "reviews:review",
            "completeness:read",
            "completeness:recalculate",
            "dashboard:read",
            "dashboard:write",
            "imports:read",
            "imports:write",
            "exports:read",
            "operation_logs:read",
        ],
    },
    "center_manager": {
        "label": "中心负责人",
        "description": "管理指定中心",
        "permissions": [
            "master_data:read",
            "dictionaries:read",
            "clinical_data:read",
            "clinical_data:write",
            "pdf_packets:read",
            "pdf_packets:write",
            "pdf_review:read",
            "pdf_review:annotate",
            "pdf_review:manage",
            "correction_tasks:read",
            "correction_tasks:create",
            "correction_tasks:submit",
            "correction_tasks:review",
            "files:read",
            "files:write",
            "image_data:read",
            "image_data:upload_raw",
            "image_data:upload_report",
            "reviews:read",
            "reviews:submit",
            "completeness:read",
            "completeness:recalculate",
            "dashboard:read",
            "dashboard:write",
            "imports:read",
            "imports:write",
            "exports:read",
            "operation_logs:read",
        ],
    },
    "clinical_coordinator": {
        "label": "临床协调员",
        "description": "上传和维护资料",
        "permissions": [
            "master_data:read",
            "dictionaries:read",
            "clinical_data:read",
            "clinical_data:write",
            "pdf_packets:read",
            "pdf_packets:write",
            "pdf_review:read",
            "correction_tasks:read",
            "correction_tasks:submit",
            "files:read",
            "files:write",
            "image_data:read",
            "image_data:upload_raw",
            "image_data:upload_report",
            "reviews:read",
            "reviews:submit",
            "completeness:read",
            "completeness:recalculate",
            "dashboard:read",
            "dashboard:write",
            "imports:read",
            "imports:write",
            "exports:read",
        ],
    },
    "reviewer": {
        "label": "审核人员",
        "description": "审核文件和数据项",
        "permissions": [
            "master_data:read",
            "dictionaries:read",
            "clinical_data:read",
            "pdf_packets:read",
            "pdf_review:read",
            "pdf_review:annotate",
            "correction_tasks:read",
            "correction_tasks:create",
            "correction_tasks:review",
            "files:read",
            "image_data:read",
            "reviews:read",
            "reviews:review",
            "completeness:read",
            "completeness:recalculate",
            "dashboard:read",
            "exports:read",
        ],
    },
    "rd_user": {
        "label": "研发人员",
        "description": "查看临床数据、访问研发数据模块",
        "permissions": [
            "master_data:read",
            "dictionaries:read",
            "clinical_data:read",
            "pdf_packets:read",
            "pdf_review:read",
            "files:read",
            "image_data:read",
            "image_data:copy_raw",
            "image_data:upload_enhanced",
            "reviews:read",
            "completeness:read",
            "dashboard:read",
            "exports:read",
        ],
    },
    "readonly": {
        "label": "只读用户",
        "description": "只读查看",
        "permissions": [
            "master_data:read",
            "dictionaries:read",
            "clinical_data:read",
            "pdf_packets:read",
            "pdf_review:read",
            "files:read",
            "image_data:read",
            "reviews:read",
            "completeness:read",
            "dashboard:read",
            "exports:read",
        ],
    },
}
